export type Reservation = {
  id: string;
  noClients: string;
  description: string;
  dateIn: string;
  dateOut: string;
  totalCost: string;
  totalPayded: string;
  costPerClient: string;
  discount: string;
  totalNights: string;
  paymentNights: string;
  management: string;
  transport: string;
  advanceManagement: boolean;
  roomId?: string;
  clients: string[];
  createdBy: string;
  updatedBy: string;
  createdTime: string;
  updatedTime: string;
  userEmail: string;
  lodgingCostPerClient: string;
  totalCostPerClient: string;
  totalPaydedPerClient: string;
  pendingPerClient: string;
  totalPending: string;
};
